[package]
name = "yoda-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
dioxus = { workspace = true, features = ["desktop"] }
tracing.workspace = true
tracing-subscriber.workspace = true
yoda-config = { path = "../yoda-config" }
yoda-ui = { path = "../yoda-ui" }
yoda-web = { path = "../yoda-web", features = ["server"] }
tokio.workspace = true

[lints]
workspace = true
