[package]
name = "yoda-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
dioxus.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
urlencoding.workspace = true
yoda-app = { path = "../yoda-app" }
yoda-core = { path = "../yoda-core" }
yoda-data = { path = "../yoda-data" }

[lints]
workspace = true