[package]
name = "yoda-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
yoda-config = { path = "../yoda-config" }
yoda-core = { path = "../yoda-core" }
yoda-data = { path = "../yoda-data" }

[dev-dependencies]
image.workspace = true
tempfile.workspace = true

[lints]
workspace = true