[package]
name = "yoda-web"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
server = ["dioxus/server"]
web = ["dioxus/web"]

[dependencies]
axum.workspace = true
dioxus = { workspace = true, features = ["fullstack"] }
dioxus-cli-config.workspace = true
dioxus-server.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
yoda-app = { path = "../yoda-app" }
yoda-ui = { path = "../yoda-ui" }

[lints]
workspace = true